services:

  mongodb:
    build:
      context: ./docker/mongodb_rs
      args:
        MONGO_VERSION: "latest" # Этот параметр передается в Dockerfile
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb-data:/data/db
