# Production

services:
  mongodb:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 'latest' # Этот параметр передается в Dockerfile
    container_name: mongodb
    restart: always
    env_file:
      - .env.production
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db

  app:
    build:
      context: ../
    container_name: app
    restart: always
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    env_file:
      - .env.production
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx-conf.d/:/etc/nginx/conf.d
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    entrypoint: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    restart: always

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    # Чтобы контейнер не выключался после завершения ставим команду sleep
    entrypoint: /bin/sh -c "sleep infinity"
