# Production

services:

  mongodb:
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: "latest" # Этот параметр передается в Dockerfile
    container_name: mongodb
    restart: always
    env_file:
      - .env.production
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db

  app:
    build:
      context: ../
    container_name: app
    restart: always
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
