import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";

import "./globals.css";
import { AdminHeader } from "./components/AdminHeader/AdminHeader";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ветлекарь",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = false;

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={montserrat.className}>
        {isAdmin ? <AdminHeader /> : <Header />}
        <main>{children}</main>
        {!isAdmin && <Footer />}
      </body>
    </html>
  );
}
